cd "C:\Users\elcio\Documents\UFFS\2022-2\IA\Trabalho\saida"
ren "CSLM128-base.txt" "Cuando Suba La Marea-128-base.txt"
ren "CSLM128-large.txt" "Cuando Suba La Marea-128-large.txt"
ren "CSLM128-medium.txt" "Cuando Suba La Marea-128-medium.txt"
ren "CSLM128-small.txt" "Cuando Suba La Marea-128-small.txt"
ren "CSLM128-tiny.txt" "Cuando Suba La Marea-128-tiny.txt"
ren "CSLM192-base.txt" "Cuando Suba La Marea-192-base.txt"
ren "CSLM192-large.txt" "Cuando Suba La Marea-192-large.txt"
ren "CSLM192-medium.txt" "Cuando Suba La Marea-192-medium.txt"
ren "CSLM192-small.txt" "Cuando Suba La Marea-192-small.txt"
ren "CSLM192-tiny.txt" "Cuando Suba La Marea-192-tiny.txt"
ren "CSLM256-base.txt" "Cuando Suba La Marea-256-base.txt"
ren "CSLM256-large.txt" "Cuando Suba La Marea-256-large.txt"
ren "CSLM256-medium.txt" "Cuando Suba La Marea-256-medium.txt"
ren "CSLM256-small.txt" "Cuando Suba La Marea-256-small.txt"
ren "CSLM256-tiny.txt" "Cuando Suba La Marea-256-tiny.txt"
ren "CSLM320-base.txt" "Cuando Suba La Marea-320-base.txt"
ren "CSLM320-large.txt" "Cuando Suba La Marea-320-large.txt"
ren "CSLM320-medium.txt" "Cuando Suba La Marea-320-medium.txt"
ren "CSLM320-small.txt" "Cuando Suba La Marea-320-small.txt"
ren "CSLM320-tiny.txt" "Cuando Suba La Marea-320-tiny.txt"
ren "CSLM64-base.txt" "Cuando Suba La Marea-64-base.txt"
ren "CSLM64-large.txt" "Cuando Suba La Marea-64-large.txt"
ren "CSLM64-medium.txt" "Cuando Suba La Marea-64-medium.txt"
ren "CSLM64-small.txt" "Cuando Suba La Marea-64-small.txt"
ren "CSLM64-tiny.txt" "Cuando Suba La Marea-64-tiny.txt"
ren "FC128-base.txt" "Faroeste Caboclo-128-base.txt"
ren "FC128-large.txt" "Faroeste Caboclo-128-large.txt"
ren "FC128-medium.txt" "Faroeste Caboclo-128-medium.txt"
ren "FC128-small.txt" "Faroeste Caboclo-128-small.txt"
ren "FC128-tiny.txt" "Faroeste Caboclo-128-tiny.txt"
ren "FC192-base.txt" "Faroeste Caboclo-192-base.txt"
ren "FC192-large.txt" "Faroeste Caboclo-192-large.txt"
ren "FC192-medium.txt" "Faroeste Caboclo-192-medium.txt"
ren "FC192-small.txt" "Faroeste Caboclo-192-small.txt"
ren "FC192-tiny.txt" "Faroeste Caboclo-192-tiny.txt"
ren "FC256-base.txt" "Faroeste Caboclo-256-base.txt"
ren "FC256-large.txt" "Faroeste Caboclo-256-large.txt"
ren "FC256-medium.txt" "Faroeste Caboclo-256-medium.txt"
ren "FC256-small.txt" "Faroeste Caboclo-256-small.txt"
ren "FC256-tiny.txt" "Faroeste Caboclo-256-tiny.txt"
ren "FC320-base.txt" "Faroeste Caboclo-320-base.txt"
ren "FC320-large.txt" "Faroeste Caboclo-320-large.txt"
ren "FC320-medium.txt" "Faroeste Caboclo-320-medium.txt"
ren "FC320-small.txt" "Faroeste Caboclo-320-small.txt"
ren "FC320-tiny.txt" "Faroeste Caboclo-320-tiny.txt"
ren "FC64-base.txt" "Faroeste Caboclo-64-base.txt"
ren "FC64-large.txt" "Faroeste Caboclo-64-large.txt"
ren "FC64-medium.txt" "Faroeste Caboclo-64-medium.txt"
ren "FC64-small.txt" "Faroeste Caboclo-64-small.txt"
ren "FC64-tiny.txt" "Faroeste Caboclo-64-tiny.txt"
pause